export const SET_EXPRESSION = "SET_EXPRESSION";
export const CLEAR = "CLEAR";
export const CLEAR_LAST_ENTRY = "CLEAR_LAST_ENTRY";
export const EVALUATE_EXPRESSION = "EVALUATE_EXPRESSION";
export const SQUARE_ROOT = "SQUARE_ROOT";
export const SQUARE = "SQUARE"